### ISSUE TITLE
error: unknown type name 'PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC'

### ISSUE THREAD

**Issue by jw20082009** [keith2018/SharedTexture#2]
![image](https://github.com/keith2018/SharedTexture/assets/8803478/65128146-a90e-4336-9835-fdd38697c407)

**Comment by keith2018** [comment]
Try upgrade your Android NDK version 
or copy `eglext.h` from [https://registry.khronos.org/EGL/api/EGL/eglext.h](https://registry.khronos.org/EGL/api/EGL/eglext.h)
